---
title: "heat_index"
author: "JEON"
editor_options: 
  chunk_output_type: console
---
```{r, message=FALSE}

setwd("D:/workspace/ds_yonsei/project")

library(readr)
library(tidyverse)
library(sf)
library(leaflet)

```

```{r files}

grid_sf <- st_read("grid/grid.shp") # 그리드
heat_df <- read.csv("final_variable.csv", header = TRUE) # 열섬 요소

heat_index <- read_csv("heat.csv")
heat_index <- heat_index[,c(1,4)]
colnames(heat_index)[2] <- "index" 
heat_df <- left_join(heat_df, heat_index, by="fid")

heat_sf  <- grid_sf %>% left_join(heat_df, by = c("fid"="fid"))
heat_sf$label <- heat_sf$label %>% as.character() %>% as.factor()

```

```{r index}



## 팔레트
index_pal  <- colorFactor(c("yellow","red"), domain = heat_sf$index)

## 라벨
index_labels <- sprintf(
  "<strong>cluster : %s</strong><br/> fid : %g <br/> average temperature : %g\u00B0C",
  heat_sf$label, heat_sf$fid, heat_sf$avg_tmp 
) %>% lapply(htmltools::HTML)

leaflet(heat_sf) %>%
  addTiles() %>% 
  addPolygons(opacity = 1.0, fillOpacity = 0.8,
              weight = 1,
              fillColor = ~index_pal(index),
              highlightOptions = highlightOptions(color = "black", weight = 3,  bringToFront = TRUE),
              label = index_labels,
              labelOptions = labelOptions(
              style = list("font-weight" = "normal", padding = "3px 8px"),
              textsize = "15px",
              direction = "auto")) %>%
    addLegend("bottomright", pal = index_pal, values = ~index,
    title = "열섬 측도",
    labFormat = labelFormat(suffix = "점"),
    opacity = 1)
```